export const GET_PAGINATED_USERS = 'GET_PAGINATED_USERS'
export const PAGINATED_USERS_ERROR = 'PAGINATED_USERS_ERROR'
export const GET_NUMBER_OF_ALL_USERS = 'GET_NUMBER_OF_ALL_USERS'
export const NUMBER_OF_ALL_USERS_ERROR = 'NUMBER_OF_ALL_USERS_ERROR'